define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "ContentHealthManagerTitle": "Content Health Manager",
    "ContentHealthManagerDescription": "This application helps you analyze and maintain the health of your SharePoint content by identifying broken links, finding outdated content based on modification dates, and detecting checked-out items that may need attention. Use this tool to ensure your SharePoint sites remain organized and accessible.",
    "HowToUseHeading": "How to use:",
    "FirstSelectSites": "First, select sites - Choose all the SharePoint sites you want to analyze from the site picker below.",
    "SecondSelectSingleSite": "Second, select a single site - From the dropdown, pick one specific site to process and analyze.",
    "StartQueryToFind": "Start query to find:",
    "BrokenLinksInPages": "Broken links in pages",
    "OldContentForDate": "Old content for a given start date",
    "CheckedOutContentItems": "Checked out content items",
    "SelectFirstAllSites": "Select first all sites that you want to query and process",
    "SelectSitesLabel": "Select sites",
    "SelectAllSitesPlaceholder": "Select all sites to process...",
    "FilterSitesPlaceholder": "Filter sites",
    "ToContinueSelectSite": "To continue, please select first a site to process",
    "ChooseSiteLabel": "Choose a Site",
    "SelectSitePlaceholder": "Select a Site to process",
    "ResultsForSite": "Results for site:",
    "BrokenLinksAnalysisTab": "Broken Links Analysis",
    "LibraryAnalysisTab": "Library Analysis",
    "SelectDateLabel": "Select a date",
    "SelectQueryDatePlaceholder": "Select a query date...",
    "QueryAllLibraries": "Query all libraries",
    "QueryLibrary": "Query library",
    "CheckedOutItems": "Checked-out items",
    "OpenDetails": "Open details",
    "LibrariesCheckbox": "Libraries",
    "ListsCheckbox": "Lists",
    "FindBrokenLinks": "Find broken links",
    "ProcessPage": "Process page",
    "PageReportTitle": "Page report",
    "TitleLabel": "Title:",
    "UrlLabel": "URL:",
    "TotalLinksLabel": "Total links:",
    "BrokenLinksLabel": "Broken links:",
    "AllLinksLabel": "All Links:",
    "ShowOnlyBrokenLinks": "Show only broken links",
    "NoTitle": "No title",
    "ShowContent": "Show Content",
    "NoBrokenLinksFound": "No broken links found on this page.",
    "NoLinksFound": "No links found on this page.",
    "NoLinkAnalysisAvailable": "No link analysis available.",
    "NoItemSelected": "No item selected.",
    "CloseButton": "Close",
    "LibraryReportTitle": "Library report",
    "TemplateLabel": "Template:",
    "DescriptionLabel": "Description:",
    "ItemCountLabel": "Item Count:",
    "CreatedLabel": "Created:",
    "LastModifiedLabel": "Last Modified:",
    "LastUserModifiedLabel": "Last User Modified:",
    "LastDeletedLabel": "Last Deleted:",
    "EnableVersioningLabel": "Enable Versioning:",
    "EnableAttachmentsLabel": "Enable Attachments:",
    "EnableFolderCreationLabel": "Enable Folder Creation:",
    "OverviewListEntries": "Overview list entries",
    "TotalItemsFound": "Total items found:",
    "ShowPermissions": "Show Permissions",
    "QueryLibraryForResults": "Query the library for results",
    "NoLibrarySelected": "No library selected.",
    "Yes": "Yes",
    "No": "No",
    "NA": "N/A",
    "FoundLabel": "Found",
    "StartQueryForResults": "start query fo results",
    "CreatedAtLabel": "created at",
    "LastChangeLabel": "Last change",
    "UserChangedLabel": "User changed",
    "LastDeletionLabel": "last deletion",
    "FoundLinksCount": "Found {0}. Broken links: {1}",
    "BrokenLinksCount": "Broken links: {0}"
  }
});