"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListTemplateType = void 0;
//https://learn.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee541191(v=office.15)
var ListTemplateType;
(function (ListTemplateType) {
    ListTemplateType[ListTemplateType["InvalidType"] = -1] = "InvalidType";
    ListTemplateType[ListTemplateType["NoListTemplate"] = 0] = "NoListTemplate";
    ListTemplateType[ListTemplateType["GenericList"] = 100] = "GenericList";
    ListTemplateType[ListTemplateType["DocumentLibrary"] = 101] = "DocumentLibrary";
    ListTemplateType[ListTemplateType["Survey"] = 102] = "Survey";
    ListTemplateType[ListTemplateType["Links"] = 103] = "Links";
    ListTemplateType[ListTemplateType["Announcements"] = 104] = "Announcements";
    ListTemplateType[ListTemplateType["Contacts"] = 105] = "Contacts";
    ListTemplateType[ListTemplateType["Events"] = 106] = "Events";
    ListTemplateType[ListTemplateType["Tasks"] = 107] = "Tasks";
    ListTemplateType[ListTemplateType["DiscussionBoard"] = 108] = "DiscussionBoard";
    ListTemplateType[ListTemplateType["PictureLibrary"] = 109] = "PictureLibrary";
    ListTemplateType[ListTemplateType["DataSources"] = 110] = "DataSources";
    ListTemplateType[ListTemplateType["WebTemplateCatalog"] = 111] = "WebTemplateCatalog";
    ListTemplateType[ListTemplateType["UserInformation"] = 112] = "UserInformation";
    ListTemplateType[ListTemplateType["WebPartCatalog"] = 113] = "WebPartCatalog";
    ListTemplateType[ListTemplateType["ListTemplateCatalog"] = 114] = "ListTemplateCatalog";
    ListTemplateType[ListTemplateType["XMLForm"] = 115] = "XMLForm";
    ListTemplateType[ListTemplateType["MasterPageCatalog"] = 116] = "MasterPageCatalog";
    ListTemplateType[ListTemplateType["NoCodeWorkflows"] = 117] = "NoCodeWorkflows";
    ListTemplateType[ListTemplateType["WorkflowProcess"] = 118] = "WorkflowProcess";
    ListTemplateType[ListTemplateType["WebPageLibrary"] = 119] = "WebPageLibrary";
    ListTemplateType[ListTemplateType["CustomGrid"] = 120] = "CustomGrid";
    ListTemplateType[ListTemplateType["SolutionCatalog"] = 121] = "SolutionCatalog";
    ListTemplateType[ListTemplateType["NoCodePublic"] = 122] = "NoCodePublic";
    ListTemplateType[ListTemplateType["ThemeCatalog"] = 123] = "ThemeCatalog";
    ListTemplateType[ListTemplateType["DesignCatalog"] = 124] = "DesignCatalog";
    ListTemplateType[ListTemplateType["AppDataCatalog"] = 125] = "AppDataCatalog";
    ListTemplateType[ListTemplateType["AppFiles"] = 126] = "AppFiles";
    ListTemplateType[ListTemplateType["DataConnectionLibrary"] = 130] = "DataConnectionLibrary";
    ListTemplateType[ListTemplateType["WorkflowHistory"] = 140] = "WorkflowHistory";
    ListTemplateType[ListTemplateType["GanttTasks"] = 150] = "GanttTasks";
    ListTemplateType[ListTemplateType["HelpLibrary"] = 151] = "HelpLibrary";
    ListTemplateType[ListTemplateType["AccessRequest"] = 160] = "AccessRequest";
    ListTemplateType[ListTemplateType["TasksWithTimelineAndHierarchy"] = 171] = "TasksWithTimelineAndHierarchy";
    ListTemplateType[ListTemplateType["MaintenanceLogs"] = 175] = "MaintenanceLogs";
    ListTemplateType[ListTemplateType["Meetings"] = 200] = "Meetings";
    ListTemplateType[ListTemplateType["Agenda"] = 201] = "Agenda";
    ListTemplateType[ListTemplateType["MeetingUser"] = 202] = "MeetingUser";
    ListTemplateType[ListTemplateType["Decision"] = 204] = "Decision";
    ListTemplateType[ListTemplateType["MeetingObjective"] = 207] = "MeetingObjective";
    ListTemplateType[ListTemplateType["TextBox"] = 210] = "TextBox";
    ListTemplateType[ListTemplateType["ThingsToBring"] = 211] = "ThingsToBring";
    ListTemplateType[ListTemplateType["HomePageLibrary"] = 212] = "HomePageLibrary";
    ListTemplateType[ListTemplateType["Posts"] = 301] = "Posts";
    ListTemplateType[ListTemplateType["Comments"] = 302] = "Comments";
    ListTemplateType[ListTemplateType["Categories"] = 303] = "Categories";
    ListTemplateType[ListTemplateType["Facility"] = 402] = "Facility";
    ListTemplateType[ListTemplateType["Whereabouts"] = 403] = "Whereabouts";
    ListTemplateType[ListTemplateType["CallTrack"] = 404] = "CallTrack";
    ListTemplateType[ListTemplateType["Circulation"] = 405] = "Circulation";
    ListTemplateType[ListTemplateType["Timecard"] = 420] = "Timecard";
    ListTemplateType[ListTemplateType["Holidays"] = 421] = "Holidays";
    ListTemplateType[ListTemplateType["IMEDic"] = 499] = "IMEDic";
    ListTemplateType[ListTemplateType["ExternalList"] = 600] = "ExternalList";
    ListTemplateType[ListTemplateType["MySiteDocumentLibrary"] = 700] = "MySiteDocumentLibrary";
    ListTemplateType[ListTemplateType["Forms"] = 10102] = "Forms";
    ListTemplateType[ListTemplateType["IssueTracking"] = 1100] = "IssueTracking";
    ListTemplateType[ListTemplateType["AdminTasks"] = 1200] = "AdminTasks";
    ListTemplateType[ListTemplateType["HealthRules"] = 1220] = "HealthRules";
    ListTemplateType[ListTemplateType["HealthReports"] = 1221] = "HealthReports";
    ListTemplateType[ListTemplateType["DeveloperSiteDraftApps"] = 1230] = "DeveloperSiteDraftApps";
    ListTemplateType[ListTemplateType["ConnectedLinks"] = 3300] = "ConnectedLinks";
    ListTemplateType[ListTemplateType["ExtendedWebSiteTemplates"] = 3415] = "ExtendedWebSiteTemplates";
})(ListTemplateType || (exports.ListTemplateType = ListTemplateType = {}));
//export type ListTemplateType = typeof ListTemplateType[keyof typeof ListTemplateType];
//# sourceMappingURL=ListTemplateTypes.js.map