define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "ContentHealthManagerTitle": "Content Health Manager",
    "ContentHealthManagerDescription": "This application helps you analyze and maintain the health of your SharePoint content by identifying broken links, finding outdated content based on modification dates, detecting checked-out items that may need attention, and surfacing pages waiting for approval. It also lets you review the permissions on pages, libraries, and found items to check who has access. Use this tool to ensure your SharePoint sites remain organized, accessible, and secure.",
    "HowToUseHeading": "How to use:",
    "FirstSelectSites": "First, select sites - Choose all the SharePoint sites you want to analyze from the site picker below.",
    "SecondSelectSingleSite": "Second, select a single site - From the dropdown, pick one specific site to process and analyze.",
    "StartQueryToFind": "Start query to find:",
    "BrokenLinksInPages": "Broken links in pages",
    "OldContentForDate": "Old content for a given start date",
    "CheckedOutContentItems": "Checked out content items",
    "PagesWaitingForApproval": "Pages waiting for approval",
    "FourthCheckPermissions": "Fourth, check permissions - Use the Permissions button on a page, library, or found item to see who has access, inspect SharePoint groups and their members, and verify access for a specific person or group.",
    "SelectFirstAllSites": "Select first all sites that you want to query and process",
    "SelectSitesLabel": "Select sites",
    "SelectAllSitesPlaceholder": "Select all sites to process...",
    "FilterSitesPlaceholder": "Filter sites",
    "ToContinueSelectSite": "To continue, please select first a site to process",
    "ChooseSiteLabel": "Choose a Site",
    "SelectSitePlaceholder": "Select a Site to process",
    "ResultsForSite": "Results for site:",
    "BrokenLinksAnalysisTab": "Page Library",
    "LibraryAnalysisTab": "Library Analysis",
    "SelectDateLabel": "Select a date",
    "SelectQueryDatePlaceholder": "Select a query date...",
    "SelectDateHint": "Select a date below. The buttons in this section use it to filter results: only items created or modified since that date are included, whether you query libraries and lists or look for checked-out items.",
    "QueryAllLibraries": "Query all libraries",
    "QueryLibrary": "Query library",
    "CheckedOutItems": "Checked-out items",
    "OpenDetails": "Open details",
    "LibrariesCheckbox": "Libraries",
    "ListsCheckbox": "Lists",
    "FindBrokenLinks": "Find broken links",
    "ProcessPage": "Process page",
    "TooltipQueryAllLibraries": "Scan every library and list on this site for items created or modified since the selected date",
    "TooltipQueryLibrary": "Scan the selected library or list for items created or modified since the selected date",
    "TooltipCheckedOutItems": "Find items that are currently checked out across all libraries and lists on this site",
    "TooltipOpenLibraryDetails": "Open a detailed report for the selected library, including matched items and permissions",
    "TooltipFindBrokenLinks": "Scan every page on this site for broken links",
    "TooltipProcessPage": "Scan the selected page for broken links",
    "TooltipOpenPageDetails": "Open a detailed report of the links found on the selected page",
    "TooltipShowPermissions": "Show the SharePoint permissions for the selected item",
    "TooltipCloseDialog": "Close this dialog",
    "TooltipToggleContent": "Show or hide the raw page content captured around this link",
    "TooltipLoadPageDetails": "Load approval, permission and checkout status for every page in the list",
    "TooltipShowSelectedLibraryPermissions": "Show the SharePoint permissions for the selected library",
    "PageReportTitle": "Page report",
    "TitleLabel": "Title:",
    "UrlLabel": "URL:",
    "TotalLinksLabel": "Total links:",
    "BrokenLinksLabel": "Broken links:",
    "AllLinksLabel": "All Links:",
    "ShowOnlyBrokenLinks": "Show only broken links",
    "NoTitle": "No title",
    "ShowContent": "Show Content",
    "NoBrokenLinksFound": "No broken links found on this page.",
    "NoLinksFound": "No links found on this page.",
    "NoLinkAnalysisAvailable": "No link analysis available.",
    "NoItemSelected": "No item selected.",
    "CloseButton": "Close",
    "LibraryReportTitle": "Library report",
    "TemplateLabel": "Template:",
    "DescriptionLabel": "Description:",
    "ItemCountLabel": "Item Count:",
    "CreatedLabel": "Created:",
    "LastModifiedLabel": "Last Modified:",
    "LastUserModifiedLabel": "Last User Modified:",
    "LastDeletedLabel": "Last Deleted:",
    "EnableVersioningLabel": "Enable Versioning:",
    "EnableAttachmentsLabel": "Enable Attachments:",
    "EnableFolderCreationLabel": "Enable Folder Creation:",
    "OverviewListEntries": "Overview list entries",
    "TotalItemsFound": "Total items found:",
    "TotalCheckedOutIemsFound": "Total checked-out items found:",
    "ShowPermissions": "Show Permissions",
    "QueryLibraryForResults": "Query the library for results",
    "NoLibrarySelected": "No library selected.",
    "Yes": "Yes",
    "No": "No",
    "NA": "N/A",
    "PermissionsButtonLabel": "Permissions",
    "PagePermissionsTitle": "Page permissions",
    "PagesLibraryLabel": "Site Pages library",
    "TooltipShowLibraryPermissions": "Show the SharePoint permissions for the site's pages library",
    "PrincipalNameLabel": "Name",
    "PrincipalTypeLabel": "Type",
    "LoginNameLabel": "Login name",
    "RolesLabel": "Roles",
    "GroupLabel": "Group",
    "UserLabel": "User",
    "NoPermissionsFound": "No permissions found for this item.",
    "NoNestedGroups": "No nested groups.",
    "EmailLabel": "Email",
    "SearchUserOrGroupPlaceholder": "Search for a user or group...",
    "HasAccessLabel": "{0} has access — Permission level: {1}",
    "NoAccessLabel": "{0} does not have access to this item.",
    "FullControlLabel": "Full Control",
    "DesignLabel": "Design",
    "EditLabel": "Edit",
    "ContributeLabel": "Contribute",
    "ReadLabel": "Read",
    "NoAccessLevelLabel": "No access",
    "FoundLabel": "Found",
    "StartQueryForResults": "start query fo results",
    "CreatedAtLabel": "created at",
    "LastChangeLabel": "Last change",
    "UserChangedLabel": "User changed",
    "LastDeletionLabel": "last deletion",
    "FoundLinksCount": "Found {0}. Broken links: {1}",
    "BrokenLinksCount": "Broken links: {0}",
    "LoadPageDetailsButtonLabel": "Load details",
    "NeedsApprovalLabel": "Needs approval",
    "HasUniquePermissionLabel": "Unique permissions",
    "CheckedOutLabel": "Checked out",
    "NotCheckedOut": "Not checked out",
    "CheckoutNotSupported": "Not supported",
    "LibraryTypeLabel": "Document library",
    "ListTypeLabel": "List"
  }
});